## numpy

In [2]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [4]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [6]:
%timeit [x ** 2 for x in big_list]

8.65 ms ± 529 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%timeit big_array ** 2

51.9 μs ± 4.57 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Creating array

In [13]:
a = np.array([1,2,3,4]) # 1_d array
print(a)

[1 2 3 4]


In [15]:
b = np.array([[1,2,3,4],[5,6,7,8]])  # 2-d array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [19]:
zero = (np.zeros((2,3)))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [26]:
print(np.eye(3)) # identity  matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [30]:
print(rng.integers(1,10,size=(3,3)))

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [31]:
print(rng.normal(loc=0, scale = 1, size =5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


## Array Atttibutes and data types

In [36]:
M = np.array([[1,2,3,],[4,5,6,]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
print(M.ndim)

2


In [39]:
print(M.shape)

(2, 3)


In [40]:
print(M.size)

6


In [41]:
print(M.dtype)

int32


In [44]:
ints = np.array([1,2,3], dtype=np.int32)
ints.dtype

dtype('int32')

In [45]:
floats = np.array([1,2,3], dtype = np.float64)
floats.dtype

dtype('float64')

## indexing and slicing

In [46]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
print(x[4])

14


In [48]:
print(x[:4])

[10 11 12 13]


In [49]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
print(M[1,2])

7


In [51]:
print(M[1])

[5 6 7 8]


In [52]:
print(M[:,0])

[1 5 9]


## Vector operation

In [54]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [55]:
print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [56]:
print(a+b)

[11 22 33 44]


In [57]:
print(a*b)

[ 10  40  90 160]


In [58]:
# boardcasting

In [62]:
a = np.array([1,2,3])
b = 10
print(a+b)

[11 12 13]


In [65]:
a = np.array([[1,2,3],
              [4,5,6],])
b = np.array([10,20,30])